### ISSUE TITLE
Help please i dont know how to install nor how use it xD

### ISSUE THREAD

**Issue by yaasin12** [ritiek/scribd-downloader#17]
C:\Users\Yaasin\scribd-downloader>scribdl https://www.scribd.com/document/55949937/33-Strategies-of-War
Traceback (most recent call last):
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yaasin\AppData\Local\Programs\Python\Python37-32\Scripts\scribdl.exe\__main__.py", line 5, in <module>
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\scribdl\scribdl.py", line 5, in <module>
    from md2pdf.core import md2pdf
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\md2pdf\__init__.py", line 3, in <module>
    from md2pdf.core import (
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\md2pdf\core.py", line 3, in <module>
    from weasyprint import HTML, CSS
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\__init__.py", line 375, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\css\__init__.py", line 29, in <module>
    from . import computed_values
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\css\computed_values.py", line 16, in <module>
    from .. import text
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\weasyprint\text.py", line 18, in <module>
    import cairocffi as cairo
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\users\yaasin\appdata\local\programs\python\python37-32\lib\site-packages\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2

**Comment by Goliant** [comment]
Im newbie tho, had same isue for

File "c:\users\win7\appdata\local\programs\python\python37-32\lib\site-package
s\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\users\win7\appdata\local\programs\python\python37-32\lib\site-package
s\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2

am I made a mistake on installing or using it?

**Comment by ritiek** [comment]
Check out https://github.com/Kozea/CairoSVG/issues/84. It seems to have some info to install the missing library.

**Comment by WangLeeds** [comment]
I don't think it's a bug. Just because you did not install Cairo. So the tag must be dependency. I met that issue and I have resolved it smoothly.

**Comment by ritiek** [comment]
Actually, Cairo is only needed for generating PDF output. I'll push a patch so that users can atleast use the tool to generate markdown text instead of simply failing to run when Cairo isn't installed.
