### ISSUE TITLE
Problem with encode

### ISSUE THREAD

**Issue by rabdavinci** [ritiek/scribd-downloader#22]
I wanted download next doc:
https://ru.scribd.com/document/82508680/Independent-Contractor-Agreement
i run: 
scribdl https://ru.scribd.com/document/82508680/Independent-Contractor-Agreement

But getting error:
C:\Users\users_name\Desktop\scribd>scribdl https://ru.scribd.com/document/82508680/Independent-Contractor-Agreement
Independent_Contractor_Agreement___Indemnity___Civil_Law__Common_Law_

Extracting text to Independent_Contractor_Agreement___Indemnity___Civil_Law__Common_Law_.txt

3+ IKMHBKIDINF]ILK+
 foqhh~ }l ikmhbkidy fkm cl`m cfqb`h~~
  dqlb f`` n`fib~ `l~~h~ hswhk~h~ dhh~ ikn`xmiko f}}lqkhy dhh~ nl~}~ fkm
Traceback (most recent call last):
  File "C:\Python37\Scripts\scribdl-script.py", line 11, in <module>
    load_entry_point('scribd-downloader==0.1.6', 'console_scripts', 'scribdl')()
  File "C:\Python37\lib\site-packages\scribdl\scribdl.py", line 247, in command_line
    document.get_document()
  File "C:\Python37\lib\site-packages\scribdl\scribdl.py", line 101, in get_document
    train = self._save_content(jsonp, train, title, found)
  File "C:\Python37\lib\site-packages\scribdl\scribdl.py", line 151, in _save_content
    self._save_text(content, (title + '.txt'))
  File "C:\Python37\lib\site-packages\scribdl\scribdl.py", line 141, in _save_text
    feed.write(extraction)
  File "C:\Python37\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ue000' in position 17: character maps to <undefined>

**Comment by rabdavinci** [comment]
I think problem it automatically sets windows1251 encoding
Seems scribdl must use UTF-8.
How can i solve it?

**Comment by ritiek** [comment]
It seems like the document is encoded and is somehow decoded when viewing it online on Scribd. The tool seems to fetch only the encoded stuff from the document but doesn't know how to decode it. This document seems a special case. I'll take a better look on this.

**Comment by ritiek** [comment]
I get this weird stuff on my Linux box:
```
scribdl https://www.scribd.com/document/82508680/Independent-Contractor-Agreement
Independent_Contractor_Agreement___Indemnity___Civil_Law__Common_Law_

Extracting text to Independent_Contractor_Agreement___Indemnity___Civil_Law__Common_Law_.txt

3+ IKMHBKIDINF]ILK+
 foqhh~ }l ikmhbkidy fkm cl`m cfqb`h~~
  dqlb f`` n`fib~ `l~~h~ hswhk~h~ dhh~ ikn`xmiko f}}lqkhy dhh~ nl~}~ fkm
 jxmobhk}~ }cf} bfy ah f~~hq}hm fofik~}  }cf} qh~x`} dqlb }ch fn}~ lq lbi~~ilk~ ld 
  /~ hbw`lyhh~ id fky fkm /~ fohk}~+
9+ KLK"NLBWH]H FOQHHBHK]+
Dlq f whqilm ld }l yhfq~ fd}hq }ch }hqbikf}ilk ld }ci~
Foqhhbhk}  i`` kl} miqhn}`y lq ikmiqhn}`y hkofoh ik fky ax~ikh~~ }cf} nlbwh}h~
i}c + ]ci~ nlthkfk} ~cf`` fww`y }l }ch ohloqfwcinf` fqhf }cf} ikn`xmh~ f`` ld }ch
^}f}h ld BI+  foqhh~ }cf} }ci~ klk"nlbwh}h wqlti~ilk i`` kl} fmthq~h`y fddhn} }ch
`ith`icllm ld +
67+ HK]IQH FOQHHBHK]+
]ci~ Foqhhbhk} nlk}fik~ }ch hk}iqh foqhhbhk} ld }ch wfq}ih~ fkm
}chqh fqh kl l}chq wqlbi~h~ lq nlkmi}ilk~ ik fky l}chq foqhhbhk} ch}chq lqf` lq qi}}hk+
66+ ^HTHQFAI@I]Y+
Id fky wqlti~ilk ld }ci~ Foqhhbhk} ~cf`` ah ch`m }l ah iktf`im lq 
xkhkdlqnhfa`h dlq fky qhf~lk }ch qhbfikiko wqlti~ilk~ ~cf`` nlk}ikxh }l ah tf`im fkm hkdlqnhfa`h+
Id f nlxq} dikm~ }cf} fky wqlti~ilk ld }ci~ Foqhhbhk} i~ iktf`im lq xkhkdlqnhfa`h ax} }cf} ay
`ibi}iko ~xnc wqlti~ilk i} lx`m ahnlbh tf`im fkm hkdlqnhfa`h }chk ~xnc wqlti~ilk ~cf`` ah
mhhbhm }l ah qi}}hk nlk~}qxhm fkm hkdlqnhm f~ ~l `ibi}hm+
61+ FWW@INFA@H @F_+
]ci~ Foqhhbhk} ~cf`` ah olthqkhm ay }ch `f~ ld }ch ^}f}h ld 
Bi~~i~~iwwi+
WFQ]Y NLK]QFN]IKO ^HQTINH^:
FNH Nlqw
Ay: 
Jlck ^bi}c
Wqikniwf`
^HQTINH WQLTIMHQ:
SYZ Ikn+
Ay: 
^f``y Jlkh~
^hnqh}fqy"]qhf~xqhq 
```

but if you look carefully, you'll notice the letters here represent a different letter respectively when viewing the document online on Scribd.

**Comment by rabdavinci** [comment]
Thank you a lot!
